CREATE TABLE `IS_CM_VALUE_LIST` (
  `ID` bigint(20) NOT NULL DEFAULT '0',
  `NAME` varchar(100) NOT NULL DEFAULT '',
  `SHORTCUT` varchar(50) NOT NULL DEFAULT '',
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `CREATOR_ID` bigint(20) DEFAULT NULL,
  `CREATOR_NAME` varchar(255) NOT NULL,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIER_ID` bigint(20) DEFAULT NULL,
  `MODIFIER_NAME` varchar(255) NOT NULL,
  `MODIFICATION_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_VALUELIST_SHORTCUT` (`SHORTCUT`),
  KEY `FK_CB_CM_VALUE_LIST_CREATOR` (`CREATOR_ID`),
  KEY `FK_CB_CM_VALUE_LIST_MODIFIER` (`MODIFIER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;
CREATE TABLE `IS_CM_VALUE_LIST_ENTRY` (
  `ID` bigint(20) NOT NULL DEFAULT '0',
  `VALUE_LIST_ID` bigint(20) NOT NULL DEFAULT '0',
  `CODE` varchar(255) NOT NULL,
  `LABEL` varchar(255) NOT NULL DEFAULT '',
  `PRIORITY` smallint(6) NOT NULL DEFAULT '0',
  `DISABLED` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CB_CM_VALUE_LIST_ENTRY_CODE` (`VALUE_LIST_ID`,`CODE`) USING BTREE,
  KEY `CB_CM_VALUE_LIST_ENTRIES_FK` (`VALUE_LIST_ID`),
  KEY `VALUE_LIST_ENTRY_INACTIVE` (`DISABLED`),
  CONSTRAINT `FK_IS_CM_VALUE_LIST_ENTRIES` FOREIGN KEY (`VALUE_LIST_ID`) REFERENCES `IS_CM_VALUE_LIST` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;